# Specifies which edition is used by the parser
# Options: 2015, 2018
edition = "2018"

# Whether to use different formatting for items and expressions if they satisfy a heuristic notion of 'small'
# Options: Default, Off, Max
use_small_heuristics = "Default"

# Use tab characters for indentation, spaces for alignment
hard_tabs = false

# Maximum width of each line
max_width = 110

# Merge multiple derives into a single one
merge_derives = true

# Unix or Windows line endings
# Options: Auto, Native, Unix, Windows
newline_style = "Unix"

# Remove nested parentheses
remove_nested_parens = true

# Reorder import and extern crate statements alphabetically in groups (a group is separated by a newline)
reorder_imports = true

# Reorder mod declarations alphabetically in group
reorder_modules = true

# Number of spaces per tab
tab_spaces = 4

# Use field initialize shorthand if possible
use_field_init_shorthand = true

# Replace uses of the try! macro by the ? shorthand
use_try_shorthand = true
